obstacle_range: 2.5
raytrace_range: 3.0
transform_tolerance: 1.0

# footprint: [[-0.35, -0.35], [-0.35, 0.35], [0.35, 0.35], [0.35, -0.35]]
robot_radius: 0.25
footprint_padding: 0.02

unknown_cost_value: 0
